Allow to unshallow submodules
Use `UNSHALLOW=y`.

Shallow submodules only cause problems.

Fixes errors such as (on git fetch):

  warning: rejected refs/tags/b3181 because shallow roots are not allowed to be updated

And (on git push):

   ! [remote rejected]   0.3.12-alt1 -> 0.3.12-alt1 (shallow update not allowed)
  error: failed to push some refs to 'gitery:packages/ollama.git'

Also, don't fetch submodules' tags as they clutter tag list (and `gum`
cannot handle it).

Signed-off-by: Vitaly Chikunov <vt@altlinux.org>